module.exports = {
  onBoarding: {
    LOGIN_SUCCESS: "Login successfully.",
    CURRENT_PASSWORD: "Current password is wrong",
    PASSWORD_CHANGED: "Password changed successfully.",
    WRONG_PASSWORD: "Password or emails is wrong.",
    USERNAME_INACTIVE: "Account is not active.Please contact to admin.",
    PAYLOAD_MISSING: "Payload missing.",
    ACCOUNT_NOT_FOUND: "Account not found.",
    VERIFICATION_CODE_SENT: "Please check your email reset password link.",
    WRONG_VERIFICATION_CODE: "Verification code is incorrect.",
    PASSWORD_RESET: "Password reset successfully.",
    EMAIL_EXIST: "Email already exist.",
    STATUS_CHANGED: "Status changed successfully",
    USER_DELETED: "User deleted successfully.",
    EMAIL_REQUIRED: "Email required.",
    PASSWORD_REQUIRED: "Password required",
    ONLY_USER_LOGIN : "Invalid credentials",
    PROFILE_UPDATED: "Profile updated successfully.",
    USER_ADDED: "User added successfully.",
    TOKEN_VALID: "This token will valid for 10 hours only.",
    INVALID_ID: "Invalid id.",
    NOT_VERIFIED: "Please verify your email first.",
    EMAIL_AVAILABLE: "You can use this email.",
    EMAIL_TAKEN: "Email is already in use.",
    OTP_MATCHED: "Verification code matched",
    INVALID_OTP: "Verification code not matched",
    OTP_SENT: "Verification code sent successfully",
    ID_REQUIRED: "Id required",
    OTP_REQUIRED: "Verification code required",
    TWO_FACTOR_SUCCESS: "Two factor authentication enabled successfully.",
    LOGIN_LINK_SENT: "Login link sent to partner successfully.",
    USER_INVITED: "User invited successfully.",
    SUCCESSFULLY_REGISTERED: "User successfully registered",
    USERNAME_VERIFIED : "Please verify your email first",
    NO_USER_EXIST : "No user exist with these credentials"
    
  },  
Item:{
  PAYLOAD_MISSING:"Payload missing.",
  ALREADY_EXIST:"Item already exits",
  CREATED:"Item created successfully",
  UPDATED:"Item updated successfully",
  DELETED:"Item deleted successfully",
  NOT_FOUND:"Item not exists"
},
  messages: {
    CARD_ADDED: "Card added successfully.",
    CARD_EXIST: "Card already exist.",
    CARD_DELETED: "Card deleted successfully.",
    DEFAULT_CARD: "Primary card set successfully.",
    PLAN_PURCHASED: "Plan purchased successfully.",
    SUBSCRIPTION_CANCELED: "Subscription cancelled successfully.",
    NOT_SUBSCRIBED: "No subscription found.",
    USER_ID_REQUIRED: "User id required",
    EXTENDED_DAYS_REQUIRED: "Extend days required",
    INVALID_USER_ID: "Invalid user Id",
    TRIAL_EXTENDED: "Trial extended successfully",
  },

  category: {
    ALREADY_EXIST: "Category already exist.",
    CREATED: "Category created successfully.",
    UPDATED: "Category updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Category deleted successfully.",
    ASSOCAITED_WITH_FEATURE:
      "Unable to delete category as assocciated with features.",
    ORDER_UPDATED: "Category order updated Successfully.",
  },

  features: {
    ALREADY_EXIST: "Feature already exist.",
    CREATED: "Feature created successfully.",
    UPDATED: "Feature updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Feature deleted successfully.",
    ORDER_UPDATED: "Feature order updated successfully.",
  },

  plan: {
    ALREADY_EXIST: "Plan already exist.",
    CREATED: "Plan created successfully.",
    UPDATED: "Plan updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Plan deleted successfully.",
    ORDER_UPDATED: "Plan order updated successfully.",
  },

  pos: {
    ALREADY_EXIST: "Pos already exist.",
    CREATED: "Pos added successfully.",
    UPDATED: "Pos updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Pos deleted successfully.",
    UPDATING:
      "Pos is updating. Please wait 1 to 2 minutes for changes reflection.",
  },

  COMMON: {
    SUCCESS: "Success",
    INVALID_COUNTRY_CODE: "Invalid country code",
    SERVER_ERROR: "Something Went Wrong. Please try again.",
    UNAUTHORIZED: "You are not authorized to perform this operation",
    STATUS_CHANGED: "Status Change Successfully",
    NOT_VALID_FILE: "Invalid File Type",
    ID_REQUIRED: "Id required",
    INVALID_ID: "Invalid Id",
    UNSUPPORTED_API_VERSION: "You are using unsupported version of API",
    API_NOT_EXIST: "This API no longer exists",
    INVALID_COORDINATES: "Invalid coordinates",
    SMTP_NOT_FOUND: "Smtp not found",
    MODEL_NAME_REQUIRED: "Model name required",
    UNPROCESSABLE_DATA: "Unprocessable data",
  },

  faqs: {
    ALREADY_EXIST: "Faq already exist.",
    CREATED: "Faq created successfully.",
    UPDATED: "Faq updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "Faq deleted successfully.",
  },
  DEPARTMENT: {
    ALREADY_EXIST: "department already exist.",
    CREATED: "department created successfully.",
    UPDATED: "department updated successfully.",
    STATUS_CHANGED: "Status changed successfully.",
    DELETED: "department deleted successfully.",
    PAYLOAD_MISSING:" department name is required",
    ID_MISSING: "Id is missing",
    FETCHED : "Data Fetched successfully"
  },

};
